# Generated by Django 4.2.9 on 2024-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="author",),
        migrations.RemoveField(model_name="blogpost", name="created_at",),
        migrations.RemoveField(model_name="blogpost", name="updated_at",),
        migrations.AddField(
            model_name="blogpost",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
