# Generated by Django 4.2.9 on 2024-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blogpost_author_remove_blogpost_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogpost", name="image_url",),
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
